# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14QPjQZMK_5FuHPwa-A6K4JaWynk9xJ56
"""

# Personal Finance Chatbot using IBM Granite 3.2-2B
# Run this in Google Colab

# Install required packages
!pip install -q transformers accelerate torch gradio

import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Initialize model and tokenizer
MODEL_NAME = "ibm-granite/granite-3.2-2b-instruct"

print("Loading model and tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.bfloat16
)
print("Model loaded successfully!")

# System prompts for different user types
SYSTEM_PROMPTS = {
    "student": """You are a friendly and supportive Personal Finance Assistant designed for students.
    Use simple language, relatable examples (like managing student loans, part-time income, and budgeting for textbooks),
    and an encouraging tone. Focus on building financial literacy basics and practical money management tips for young adults.""",

    "professional": """You are an expert Personal Finance Advisor for working professionals.
    Provide sophisticated financial guidance on investment strategies, tax optimization, retirement planning,
    and wealth management. Use professional terminology while remaining clear and actionable.
    Focus on long-term financial growth and advanced planning strategies."""
}

def generate_response(message, history, user_type, temperature, max_tokens):
    """Generate chatbot response based on user type and conversation history"""

    # Select appropriate system prompt
    system_prompt = SYSTEM_PROMPTS.get(user_type.lower(), SYSTEM_PROMPTS["professional"])

    # Build conversation context
    conversation = f"{system_prompt}\n\n"

    # Add conversation history
    for user_msg, bot_msg in history:
        conversation += f"User: {user_msg}\nAssistant: {bot_msg}\n"

    # Add current message
    conversation += f"User: {message}\nAssistant:"

    # Tokenize input
    inputs = tokenizer(conversation, return_tensors="pt").to(model.device)

    # Generate response
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_tokens,
            temperature=temperature,
            do_sample=True,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id
        )

    # Decode response
    full_response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract only the assistant's response
    response = full_response.split("Assistant:")[-1].strip()

    return response

def chat_interface(message, history, user_type, temperature, max_tokens):
    """Gradio chat interface function"""
    response = generate_response(message, history, user_type, temperature, max_tokens)
    return response

# Sample financial queries for different user types
student_examples = [
    ["How can I start saving money as a college student?"],
    ["What's a good budget breakdown for someone earning $1000/month?"],
    ["Should I pay off student loans or start investing first?"]
]

professional_examples = [
    ["What are the best tax-advantaged investment accounts for high earners?"],
    ["How should I diversify my portfolio for retirement in 20 years?"],
    ["Explain the benefits of backdoor Roth IRA conversions."]
]

# Create Gradio interface
with gr.Blocks(theme=gr.themes.Soft(), title="Personal Finance Chatbot") as demo:
    gr.Markdown("""
    # 💰 Personal Finance Chatbot
    ### Powered by IBM Granite 3.2-2B Instruct Model

    Get personalized financial guidance tailored to your needs! Select your profile type and ask questions about:
    - **Savings & Budgeting** 💵
    - **Taxes & Deductions** 📊
    - **Investments & Retirement** 📈
    - **Spending Insights** 💳
    """)

    with gr.Row():
        with gr.Column(scale=3):
            chatbot = gr.Chatbot(
                height=500,
                label="Financial Advisor Chat",
                bubble_full_width=False
            )

            with gr.Row():
                user_input = gr.Textbox(
                    placeholder="Ask me anything about personal finance...",
                    label="Your Question",
                    scale=4
                )
                submit_btn = gr.Button("Send 💬", scale=1, variant="primary")

            with gr.Accordion("Example Questions", open=False):
                gr.Markdown("**For Students:**")
                student_ex = gr.Examples(
                    examples=student_examples,
                    inputs=user_input
                )
                gr.Markdown("**For Professionals:**")
                professional_ex = gr.Examples(
                    examples=professional_examples,
                    inputs=user_input
                )

        with gr.Column(scale=1):
            gr.Markdown("### ⚙️ Settings")

            user_type = gr.Radio(
                choices=["Student", "Professional"],
                value="Professional",
                label="User Profile",
                info="Chatbot will adapt its tone and complexity"
            )

            temperature = gr.Slider(
                minimum=0.1,
                maximum=1.0,
                value=0.7,
                step=0.1,
                label="Creativity (Temperature)",
                info="Higher = more creative responses"
            )

            max_tokens = gr.Slider(
                minimum=100,
                maximum=1000,
                value=300,
                step=50,
                label="Response Length (Max Tokens)",
                info="Maximum words in response"
            )

            clear_btn = gr.Button("🗑️ Clear Chat", variant="secondary")

    gr.Markdown("""
    ---
    **Disclaimer:** This chatbot provides general financial information and educational content.
    It is not a substitute for professional financial advice. Always consult with a qualified financial advisor
    for personalized recommendations.
    """)

    # Event handlers
    submit_btn.click(
        fn=chat_interface,
        inputs=[user_input, chatbot, user_type, temperature, max_tokens],
        outputs=chatbot
    ).then(
        lambda: "",
        outputs=user_input
    )

    user_input.submit(
        fn=chat_interface,
        inputs=[user_input, chatbot, user_type, temperature, max_tokens],
        outputs=chatbot
    ).then(
        lambda: "",
        outputs=user_input
    )

    clear_btn.click(lambda: None, None, chatbot, queue=False)

# Launch the app
if __name__ == "__main__":
    demo.launch(
        share=True,
        debug=True
    )

